name: Update AWS IAM data

on:
  workflow_dispatch:

  schedule:
    # Run everyday at 4AM UTC
    - cron:  '0 4 * * *'

permissions:
  contents: write

jobs:

  gather_and_update_iam_data:
    name: Gather the latest AWS IAM data and if there is new data, publish a new package version to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Gather data and check for changes
        id: gather_data
        run: |
          # Install dependencies
          npm ci

          # Copy old IAM data for changelog comparison
          cp data/json/iam.json data/json/iam.old.json

          # Gather data
          npm run gather-data

          # Setup git repo
          git config user.name 'TobiLG'
          git config user.email 'tobilg@users.noreply.github.com'

          # Add new files if there are any
          git add .

          # Publish when data changed
          if ! git diff --cached --quiet; then
            echo 'should_publish=true' >> "$GITHUB_OUTPUT"
          fi

      - name: Eventually publish new package version
        if: ${{ steps.gather_data.outputs.should_publish == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Increase package patch version
          npm --no-git-tag-version version patch
          # Update changelog
          npm run update-changelog
          # Install DuckDB
          npm run install-duckdb
          # Create tables
          npm run create-tables
          # Export data
          npm run export-data
          # Create database
          npm run copy-database
          # Create reports
          npm run create-reports
          # Add new files
          git add .
          # Commit changes
          git commit -m "[no ci] Data update on $(date '+%FT%H:%M:%S')"
          # Push to repo
          git push
          # Build package sources
          npm run build
          # Publish new version to npm registry
          npm publish
